// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu_Ed3V762m1zM5DzwaOa4au0GJii77nw',
    appId: '1:82514675096:web:dd0d91df53626e30e017ed',
    messagingSenderId: '82514675096',
    projectId: 'kigali-city-directory-f5a98',
    authDomain: 'kigali-city-directory-f5a98.firebaseapp.com',
    storageBucket: 'kigali-city-directory-f5a98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTzkQ7q0cZAitORJ7ZdtrxayMqA4WYzQ',
    appId: '1:82514675096:android:8ea482c07d982260e017ed',
    messagingSenderId: '82514675096',
    projectId: 'kigali-city-directory-f5a98',
    storageBucket: 'kigali-city-directory-f5a98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdKf_xf7dmPjU_PS2tzCWIAaZ3A-W8Awc',
    appId: '1:82514675096:ios:8345be9394b9d0fbe017ed',
    messagingSenderId: '82514675096',
    projectId: 'kigali-city-directory-f5a98',
    storageBucket: 'kigali-city-directory-f5a98.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdKf_xf7dmPjU_PS2tzCWIAaZ3A-W8Awc',
    appId: '1:82514675096:ios:8345be9394b9d0fbe017ed',
    messagingSenderId: '82514675096',
    projectId: 'kigali-city-directory-f5a98',
    storageBucket: 'kigali-city-directory-f5a98.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu_Ed3V762m1zM5DzwaOa4au0GJii77nw',
    appId: '1:82514675096:web:0c1a8bd37ced05c9e017ed',
    messagingSenderId: '82514675096',
    projectId: 'kigali-city-directory-f5a98',
    authDomain: 'kigali-city-directory-f5a98.firebaseapp.com',
    storageBucket: 'kigali-city-directory-f5a98.firebasestorage.app',
  );
}
